apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mar11-ragupdatedimage-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/mar11-ragupdatedimage-1:db3f97cd8e31bca6f96a3262f322f457a564d1a6@sha256:d5ca6e26b03df474250610dd8b9d224dac2158b54c9601c90cd9056da39d286f # use pre-built to bootstrap
          name: app-inference
